<?php

declare(strict_types=1);

namespace StageArt\Infrastructure\Pdf;

use Dompdf\Dompdf;
use Dompdf\Options;
use StageArt\Application\PrintView\PdfRendererInterface;

/**
 * Pure-PHP adapter (Dompdf) - no exec()/external binary dependency, so
 * it runs unmodified on ordinary shared PHP hosting (confirmed on
 * ConoHa). isRemoteEnabled is left off (default): the HTML this
 * receives is entirely server-generated from trusted data, so there is
 * no legitimate reason to let it fetch remote resources, and leaving
 * that capability off is a deliberate reduction of attack surface
 * rather than an oversight.
 *
 * chroot is restricted to the plugin's own assets directory: the only
 * local file Dompdf ever needs to read via a file:// URL is the bundled
 * Noto Sans JP font (see fontDirectory()), so nothing else on the
 * filesystem needs to be reachable through it.
 *
 * isPhpEnabled is turned on solely to use Dompdf's documented
 * $pdf->page_text() mechanism for "Page X / Y" footers (see
 * PrintViewHtmlRenderer) - empirically verified during Phase 4.5
 * research to be the only page-numbering approach that actually renders
 * in this Dompdf version (the CSS3 `@page { @bottom-center { content:
 * counter(page) } }` syntax did not produce visible output when tested
 * against this install). This is safe here specifically because every
 * byte of HTML fed to this renderer is generated by
 * PrintViewHtmlRenderer itself from escaped data - never from
 * unescaped request input - so the embedded <script type="text/php">
 * block this class controls is the only PHP that can ever execute.
 */
final class DompdfRenderer implements PdfRendererInterface
{
    public function render(string $html, string $paperSize, string $orientation): string
    {
        $fontDir = $this->fontDirectory();
        $fontCacheDir = $this->fontCacheDirectory();

        $options = new Options();
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isFontSubsettingEnabled', true);
        $options->set('isPhpEnabled', true);
        $options->set('defaultMediaType', 'print');
        $options->set('fontDir', $fontDir);
        $options->set('fontCache', $fontCacheDir);
        $options->set('chroot', rtrim($fontDir, '/'));

        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($html, 'UTF-8');
        $dompdf->setPaper(strtolower($paperSize), strtolower($orientation));
        $dompdf->render();

        return $dompdf->output();
    }

    private function fontDirectory(): string
    {
        if (defined('STAGEART_PLUGIN_DIR')) {
            return STAGEART_PLUGIN_DIR . 'assets/fonts/';
        }

        return __DIR__ . '/../../../assets/fonts/';
    }

    /**
     * Dompdf writes parsed-font-metrics cache files (.ufm/.ufm.json,
     * plus a copy of the .ttf itself) into whatever directory fontCache
     * points at. Pointing that at the plugin's own bundled assets/fonts
     * directory would mix generated runtime cache output into the
     * plugin's source tree; wp-content/uploads is WordPress's own
     * writable runtime-data location and is never part of the plugin's
     * source, so it is the correct place for this cache instead.
     */
    private function fontCacheDirectory(): string
    {
        if (function_exists('wp_upload_dir')) {
            $uploads = wp_upload_dir();
            $dir = rtrim($uploads['basedir'], '/') . '/stageart-print-font-cache/';

            if (! is_dir($dir)) {
                wp_mkdir_p($dir);
            }

            return $dir;
        }

        return sys_get_temp_dir() . '/stageart-print-font-cache/';
    }
}
