<?php

declare(strict_types=1);

namespace StageArt\Application\Rehearsal;

use DateTimeImmutable;
use Exception;
use InvalidArgumentException;
use StageArt\Application\Production\ProductionNotFoundException;
use StageArt\Application\Shared\TransactionManagerInterface;
use StageArt\Core\Contract\AuthorizationContract;
use StageArt\Core\Contract\IdentityContract;
use StageArt\Core\Contract\MembershipContract;
use StageArt\Core\Contract\ProductionContextContract;
use StageArt\Domain\Person\PersonId;
use StageArt\Domain\Production\ProductionId;
use StageArt\Domain\Rehearsal\Rehearsal;
use StageArt\Domain\Rehearsal\RehearsalRepositoryInterface;
use StageArt\Domain\RehearsalAttendance\RehearsalAttendance;
use StageArt\Domain\RehearsalAttendance\RehearsalAttendanceRepositoryInterface;

/**
 * Generates Phase 1 (SCHEDULE_ADJUSTMENT) RehearsalAttendance records for
 * exactly the caller-supplied `targetPersonIds` (CreateRehearsalCommand),
 * not "every active Production member" - member selection at creation
 * time is a confirmed business requirement: an unselected Production
 * member is not an Attendance target for this Rehearsal. Each supplied
 * PersonId is validated against `MembershipContract::activeProductionMemberPersonIds()`
 * (still the authoritative "who is eligible to be selected" pool - this
 * does not relax who counts as a Production member, only who among them
 * is actually targeted) and rejected with InvalidArgumentException if it
 * names someone who is not an active, Person-subject Participant of this
 * Production. Phase 2 (ATTENDANCE_CONFIRMATION) records are explicitly
 * NOT created here; they are only ever generated by ConfirmRehearsalUseCase
 * at the SCHEDULED -> CONFIRMED transition.
 *
 * StageArt Core/Module Architecture Phase 2: depends only on Core
 * Contracts (Identity/ProductionContext/Authorization/Membership), not
 * on `ProductionRepositoryInterface`/`ProductionAuthorizationService`/
 * `ParticipantRepositoryInterface` directly.
 */
final class CreateRehearsalUseCase
{
    private ProductionContextContract $productionContext;
    private RehearsalRepositoryInterface $rehearsals;
    private RehearsalAttendanceRepositoryInterface $attendances;
    private MembershipContract $membership;
    private IdentityContract $identity;
    private AuthorizationContract $authorization;
    private TransactionManagerInterface $transactions;

    public function __construct(
        ProductionContextContract $productionContext,
        RehearsalRepositoryInterface $rehearsals,
        RehearsalAttendanceRepositoryInterface $attendances,
        MembershipContract $membership,
        IdentityContract $identity,
        AuthorizationContract $authorization,
        TransactionManagerInterface $transactions
    ) {
        $this->productionContext = $productionContext;
        $this->rehearsals = $rehearsals;
        $this->attendances = $attendances;
        $this->membership = $membership;
        $this->identity = $identity;
        $this->authorization = $authorization;
        $this->transactions = $transactions;
    }

    public function execute(CreateRehearsalCommand $command): RehearsalResult
    {
        $requesterId = $this->identity->resolveCurrentPersonId($command->requestedByWordPressUserId);

        if (! $requesterId) {
            throw new RehearsalAccessDeniedException('No StageArt Person is linked to this WordPress user.');
        }

        $productionId = ProductionId::fromString($command->productionId);
        $production = $this->productionContext->getProduction($productionId);

        if (! $production) {
            throw new ProductionNotFoundException($command->productionId);
        }

        if (! $this->authorization->canForProduction($requesterId, $productionId, RehearsalCapability::MANAGE)) {
            throw new RehearsalAccessDeniedException(
                'Only the PrimaryManager or a ProductionDelegate with the REHEARSAL_MANAGER Role can create Rehearsals.'
            );
        }

        $startDateTime = $this->parseOptionalDateTime($command->startDateTime);
        $endDateTime = $this->parseOptionalDateTime($command->endDateTime);

        $activeMemberIdStrings = array_map(
            static fn (PersonId $personId): string => $personId->toString(),
            $this->membership->activeProductionMemberPersonIds($productionId)
        );

        foreach ($command->targetPersonIds as $targetPersonIdString) {
            if (! in_array($targetPersonIdString, $activeMemberIdStrings, true)) {
                throw new InvalidArgumentException(
                    "Person {$targetPersonIdString} is not an active Participant of this Production and cannot be selected as a Rehearsal Attendance target."
                );
            }
        }

        $rehearsal = $this->transactions->run(
            function () use ($productionId, $command, $startDateTime, $endDateTime): Rehearsal {
                $rehearsal = Rehearsal::create(
                    $productionId,
                    $command->title,
                    $command->description,
                    $startDateTime,
                    $endDateTime,
                    $command->timezone,
                    $command->location
                );

                $this->rehearsals->save($rehearsal);

                foreach ($command->targetPersonIds as $targetPersonIdString) {
                    $this->attendances->save(
                        RehearsalAttendance::createPhase1($rehearsal->id(), PersonId::fromString($targetPersonIdString))
                    );
                }

                return $rehearsal;
            }
        );

        return RehearsalResult::fromDomain($rehearsal);
    }

    private function parseOptionalDateTime(?string $value): ?DateTimeImmutable
    {
        if ($value === null || $value === '') {
            return null;
        }

        try {
            return new DateTimeImmutable($value);
        } catch (Exception $exception) {
            throw new InvalidArgumentException("Invalid date/time value: {$value}");
        }
    }
}
