<?php

declare(strict_types=1);

namespace StageArt\Application\Rehearsal;

use DateTimeImmutable;
use Exception;
use InvalidArgumentException;
use StageArt\Application\Production\ProductionAuthorizationService;
use StageArt\Application\Production\ProductionNotFoundException;
use StageArt\Application\Shared\TransactionManagerInterface;
use StageArt\Core\Contract\MembershipContract;
use StageArt\Domain\Production\ProductionId;
use StageArt\Domain\Production\ProductionRepositoryInterface;
use StageArt\Domain\Rehearsal\Rehearsal;
use StageArt\Domain\Rehearsal\RehearsalRepositoryInterface;
use StageArt\Domain\RehearsalAttendance\RehearsalAttendance;
use StageArt\Domain\RehearsalAttendance\RehearsalAttendanceRepositoryInterface;

/**
 * Generates Phase 1 (SCHEDULE_ADJUSTMENT) RehearsalAttendance records for
 * every current target member at creation time, per Phase 2 instruction
 * §5 - Phase 2 (ATTENDANCE_CONFIRMATION) records are explicitly NOT
 * created here; they are only ever generated by ConfirmRehearsalUseCase
 * at the SCHEDULED -> CONFIRMED transition.
 *
 * StageArt Core/Module Architecture: depends on `MembershipContract`
 * (Core boundary), not on `ParticipantRepositoryInterface`/the former
 * `ProductionMemberResolver` directly - see
 * `StageArt\Core\Adapter\CoreMembershipAdapter` for the concrete
 * implementation this resolves to today.
 */
final class CreateRehearsalUseCase
{
    private ProductionRepositoryInterface $productions;
    private RehearsalRepositoryInterface $rehearsals;
    private RehearsalAttendanceRepositoryInterface $attendances;
    private MembershipContract $membership;
    private ProductionAuthorizationService $authorization;
    private TransactionManagerInterface $transactions;

    public function __construct(
        ProductionRepositoryInterface $productions,
        RehearsalRepositoryInterface $rehearsals,
        RehearsalAttendanceRepositoryInterface $attendances,
        MembershipContract $membership,
        ProductionAuthorizationService $authorization,
        TransactionManagerInterface $transactions
    ) {
        $this->productions = $productions;
        $this->rehearsals = $rehearsals;
        $this->attendances = $attendances;
        $this->membership = $membership;
        $this->authorization = $authorization;
        $this->transactions = $transactions;
    }

    public function execute(CreateRehearsalCommand $command): RehearsalResult
    {
        $requester = $this->authorization->resolveCurrentPerson($command->requestedByWordPressUserId);

        if (! $requester) {
            throw new RehearsalAccessDeniedException('No StageArt Person is linked to this WordPress user.');
        }

        $production = $this->productions->findById(ProductionId::fromString($command->productionId));

        if (! $production) {
            throw new ProductionNotFoundException($command->productionId);
        }

        if (! $this->authorization->hasProductionCapability($requester, $production, RehearsalCapability::MANAGE)) {
            throw new RehearsalAccessDeniedException(
                'Only the PrimaryManager or a ProductionDelegate with the REHEARSAL_MANAGER Role can create Rehearsals.'
            );
        }

        $startDateTime = $this->parseOptionalDateTime($command->startDateTime);
        $endDateTime = $this->parseOptionalDateTime($command->endDateTime);

        $rehearsal = $this->transactions->run(
            function () use ($production, $command, $startDateTime, $endDateTime): Rehearsal {
                $rehearsal = Rehearsal::create(
                    $production->id(),
                    $command->title,
                    $command->description,
                    $startDateTime,
                    $endDateTime,
                    $command->timezone,
                    $command->location
                );

                $this->rehearsals->save($rehearsal);

                foreach ($this->membership->activeProductionMemberPersonIds($production->id()) as $personId) {
                    $this->attendances->save(RehearsalAttendance::createPhase1($rehearsal->id(), $personId));
                }

                return $rehearsal;
            }
        );

        return RehearsalResult::fromDomain($rehearsal);
    }

    private function parseOptionalDateTime(?string $value): ?DateTimeImmutable
    {
        if ($value === null || $value === '') {
            return null;
        }

        try {
            return new DateTimeImmutable($value);
        } catch (Exception $exception) {
            throw new InvalidArgumentException("Invalid date/time value: {$value}");
        }
    }
}
