<?php

declare(strict_types=1);

namespace StageArt\Application\Rehearsal;

use DateTimeImmutable;
use Exception;
use InvalidArgumentException;
use StageArt\Application\Production\ProductionNotFoundException;
use StageArt\Application\Shared\TransactionManagerInterface;
use StageArt\Core\Contract\AuthorizationContract;
use StageArt\Core\Contract\IdentityContract;
use StageArt\Core\Contract\MembershipContract;
use StageArt\Core\Contract\ProductionContextContract;
use StageArt\Domain\Production\ProductionId;
use StageArt\Domain\Rehearsal\Rehearsal;
use StageArt\Domain\Rehearsal\RehearsalRepositoryInterface;
use StageArt\Domain\RehearsalAttendance\RehearsalAttendance;
use StageArt\Domain\RehearsalAttendance\RehearsalAttendanceRepositoryInterface;

/**
 * Generates Phase 1 (SCHEDULE_ADJUSTMENT) RehearsalAttendance records for
 * every current target member at creation time, per Phase 2 instruction
 * §5 - Phase 2 (ATTENDANCE_CONFIRMATION) records are explicitly NOT
 * created here; they are only ever generated by ConfirmRehearsalUseCase
 * at the SCHEDULED -> CONFIRMED transition.
 *
 * StageArt Core/Module Architecture Phase 2: depends only on Core
 * Contracts (Identity/ProductionContext/Authorization/Membership), not
 * on `ProductionRepositoryInterface`/`ProductionAuthorizationService`/
 * `ParticipantRepositoryInterface` directly.
 */
final class CreateRehearsalUseCase
{
    private ProductionContextContract $productionContext;
    private RehearsalRepositoryInterface $rehearsals;
    private RehearsalAttendanceRepositoryInterface $attendances;
    private MembershipContract $membership;
    private IdentityContract $identity;
    private AuthorizationContract $authorization;
    private TransactionManagerInterface $transactions;

    public function __construct(
        ProductionContextContract $productionContext,
        RehearsalRepositoryInterface $rehearsals,
        RehearsalAttendanceRepositoryInterface $attendances,
        MembershipContract $membership,
        IdentityContract $identity,
        AuthorizationContract $authorization,
        TransactionManagerInterface $transactions
    ) {
        $this->productionContext = $productionContext;
        $this->rehearsals = $rehearsals;
        $this->attendances = $attendances;
        $this->membership = $membership;
        $this->identity = $identity;
        $this->authorization = $authorization;
        $this->transactions = $transactions;
    }

    public function execute(CreateRehearsalCommand $command): RehearsalResult
    {
        $requesterId = $this->identity->resolveCurrentPersonId($command->requestedByWordPressUserId);

        if (! $requesterId) {
            throw new RehearsalAccessDeniedException('No StageArt Person is linked to this WordPress user.');
        }

        $productionId = ProductionId::fromString($command->productionId);
        $production = $this->productionContext->getProduction($productionId);

        if (! $production) {
            throw new ProductionNotFoundException($command->productionId);
        }

        if (! $this->authorization->canForProduction($requesterId, $productionId, RehearsalCapability::MANAGE)) {
            throw new RehearsalAccessDeniedException(
                'Only the PrimaryManager or a ProductionDelegate with the REHEARSAL_MANAGER Role can create Rehearsals.'
            );
        }

        $startDateTime = $this->parseOptionalDateTime($command->startDateTime);
        $endDateTime = $this->parseOptionalDateTime($command->endDateTime);

        $rehearsal = $this->transactions->run(
            function () use ($productionId, $command, $startDateTime, $endDateTime): Rehearsal {
                $rehearsal = Rehearsal::create(
                    $productionId,
                    $command->title,
                    $command->description,
                    $startDateTime,
                    $endDateTime,
                    $command->timezone,
                    $command->location
                );

                $this->rehearsals->save($rehearsal);

                foreach ($this->membership->activeProductionMemberPersonIds($productionId) as $personId) {
                    $this->attendances->save(RehearsalAttendance::createPhase1($rehearsal->id(), $personId));
                }

                return $rehearsal;
            }
        );

        return RehearsalResult::fromDomain($rehearsal);
    }

    private function parseOptionalDateTime(?string $value): ?DateTimeImmutable
    {
        if ($value === null || $value === '') {
            return null;
        }

        try {
            return new DateTimeImmutable($value);
        } catch (Exception $exception) {
            throw new InvalidArgumentException("Invalid date/time value: {$value}");
        }
    }
}
